### ISSUE TITLE
onUpdate removed?

### ISSUE THREAD

**Issue by rgaz-flatirons** [venasolutions/react-lazy-paginated-tree#36]
The onUpdate callback was removed in https://github.com/venasolutions/react-lazy-paginated-tree/commit/b96fdc47ccd72afc0c2e78b6c9e079f2ce941acd

Oct 4 2018

Is there an alternative?

**Comment by boweihan** [comment]
@rgaz-flatirons that's correct. What is your use-case for onUpdate?

The onUpdate callback was originally added to hook up with external data stores like redux but it wasn't a good approach because it's not ideal to maintain both an external state and a local state (and try to keep them both in sync). The correct way to use external data stores is to use the component for its presentational layer only and just pass in the correct "nodes" on each update. The callback props (toggleCallback / selectCallback) can then be used to update your external data store whenever you expand or select a node.

**Comment by rgaz-flatirons** [comment]
Hello,

We are using Formik for state management.   I did implement the select and toggle callbacks, but the problem was the state I get from Formik is correct for the top level, but a step behind from the second level of the expanded tree.   

The state I'm using is a list of ids, and was using the select callback to dynamically add and remove from the Formik state for this array.  

I think my issue is that Formik's helper function and state passed in at the root, is getting confused on lower levels. The Tree List would need to be overridden and the helper functions injected at each level.   

I'll try a couple of more things, as otherwise the library easily satisfied my requirements very easily

Thanks,
Randall.

**Comment by boweihan** [comment]
@rgaz-flatirons I see. It sounds like you might be having a problem with data mutability. I'm not sure I fully understand your implementation but hearing that the top level state is working but not the nested state makes me think that it could be a problem around React and shallow state comparisons.

https://stackoverflow.com/questions/52982725/does-a-react-component-deeply-compare-props-to-check-if-rerender-is-needed

**Comment by rgaz-flatirons** [comment]
Hello,

I redid the code, referencing the dataSource I pass into the Tree component, and the selectCallback is doing what I want it to do now.
IE, instead of trying to maintain the state in peices based on the selected node, I iterate over the dataSource object tree and generate my list from that data.  

Thanks for the help, it allowed me to do a second approach and get it working.
This can be closed.
Randall
